api_url: https://www.dmxapi.com/v1
api_key: 'sk-ZNX2HgY5tAKJQvxprxde2TaDuBmTTe9ONElI2MwrkCG1AXqW'
indent: '    '
lineno: 1777
extra_lineno: 1481
max_concurrency: 20
extra_indent: '            '
problem_file: 'D:\资料\AI攻略生成比赛\基于多智能体协同的高价值信息生成-数据集相关文件\基于多智能体协同的高价值信息生成-数据集相关文件\Ai_travel\复赛数据集\dataset\question.json'
code_path: 'D:\资料\AI攻略生成比赛\基于多智能体协同的高价值信息生成-数据集相关文件\基于多智能体协同的高价值信息生成-数据集相关文件\Ai_travel\output\commit\code800'
template_file: 'D:\资料\AI攻略生成比赛\基于多智能体协同的高价值信息生成-数据集相关文件\基于多智能体协同的高价值信息生成-数据集相关文件\Ai_travel\src\template_multi_stage.py'
question_prompt: 'D:\资料\AI攻略生成比赛\基于多智能体协同的高价值信息生成-数据集相关文件\基于多智能体协同的高价值信息生成-数据集相关文件\Ai_travel\output\commit\predict.json'
log_path: 'D:\资料\AI攻略生成比赛\基于多智能体协同的高价值信息生成-数据集相关文件\基于多智能体协同的高价值信息生成-数据集相关文件\Ai_travel\output\logs'